name: "Cleanup Staging Environment"
description: "Destroy a staging environment on uncloud"

inputs:
  ssh_private_key:
    description: "SSH private key for connecting to the staging server"
    required: true
  server_ip:
    description: "IP address of the staging server"
    required: true
  deployment_name:
    description: "Name of the deployment to destroy"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup SSH
      shell: bash
      run: |
        echo "Setting up SSH configuration..."
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_ed25519_staging
        chmod 600 ~/.ssh/id_ed25519_staging
        ssh-keyscan ${{ inputs.server_ip }} >> ~/.ssh/known_hosts
        cat >> ~/.ssh/config << EOF
        Host uncloud-staging
          HostName ${{ inputs.server_ip }}
          User root
          IdentityFile ~/.ssh/id_ed25519_staging
        EOF
        chmod 600 ~/.ssh/config
        echo "SSH configuration complete"

    - name: Install uncloud CLI
      shell: bash
      run: |
        echo "Installing uncloud CLI..."
        curl -fsS https://get.uncloud.run/install.sh | sh
        echo "Uncloud CLI installed successfully"
        uc -v

    - name: Configure uncloud
      shell: bash
      run: |
        echo "Configuring uncloud..."
        mkdir -p ~/.config/uncloud
        cp .github/uncloud.yaml ~/.config/uncloud/config.yaml
        sed -i "s/STAGING_SERVER_IP/${{ inputs.server_ip }}/g" ~/.config/uncloud/config.yaml
        echo "Uncloud configuration complete"

    - name: Destroy deployment
      shell: bash
      run: |
        DEPLOYMENT_NAME="${{ inputs.deployment_name }}"
        echo "Destroying deployment: ${DEPLOYMENT_NAME}"

        # Remove all services for this deployment
        uc rm ${DEPLOYMENT_NAME}-migrator ${DEPLOYMENT_NAME}-server ${DEPLOYMENT_NAME}-worker ${DEPLOYMENT_NAME}-db ${DEPLOYMENT_NAME}-redis ${DEPLOYMENT_NAME}-unoserver ${DEPLOYMENT_NAME}-alloy 2>/dev/null || echo "Deployment may already be destroyed or doesn't exist"

        # Remove all volumes for this deployment
        yes | uc volume rm ${DEPLOYMENT_NAME}-pg-data ${DEPLOYMENT_NAME}-redis-data ${DEPLOYMENT_NAME}-alloy-config 2>/dev/null || echo "Volumes may already be removed or don't exist"

        echo "Cleanup completed for: ${DEPLOYMENT_NAME}"
