version: "3.5"
services:
  db:
    image: postgres:17.0
    env_file:
      - .env

    working_dir: /

    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "7948:5432"
    restart: unless-stopped
    networks:
      - default
    command: postgres -c logging_collector=on -c log_destination=stderr -c
      log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=60 -c
      log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M

  cache:
    image: redis:7.4-alpine
    ports:
      - "8976:6379"
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass $REDIS_HOST_PASSWORD
    volumes:
      - cache-volume:/data
    networks:
      - default

volumes:
  db-volume:
  cache-volume:
