version: "3.5"
services:
  db:
    image: ghcr.io/vija02/theopenpresenter_db:main
    env_file:
      - .env

    working_dir: /

    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "7948:5432"
    restart: unless-stopped
    networks:
      - default
    command: postgres -c logging_collector=on -c log_destination=stderr -c
      log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=60 -c
      log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M

  cache:
    image: redis:7.4-alpine
    ports:
      - "8976:6379"
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass $REDIS_HOST_PASSWORD
    volumes:
      - cache-volume:/data
    networks:
      - default

  alloy:
    image: grafana/alloy:v1.5.1
    restart: unless-stopped
    volumes:
      - ./config/alloy:/etc/alloy
    networks:
      - default
    ports:
      - "12345:12345"
      - "4318:4318"
    environment:
      REMOTE_WRITE_HOST: $REMOTE_WRITE_HOST
      REMOTE_WRITE_AUTH: $REMOTE_WRITE_AUTH
      LOKI_HOST: $LOKI_HOST
      LOKI_AUTH: $LOKI_AUTH
      TEMPO_HOST: $TEMPO_HOST
      TEMPO_AUTH: $TEMPO_AUTH
      PYROSCOPE_HOST: $PYROSCOPE_HOST
      PYROSCOPE_AUTH: $PYROSCOPE_AUTH
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental

  unoserver:
    image: philiplehmann/unoserver:3.0.1-1816
    restart: always
    ports:
      - "3000:3000"
    networks:
      - default

volumes:
  db-volume:
  cache-volume:
