version: "3.5"
services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:2.3.5
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data:
    external: true
