import { readFileSync } from "fs";
import path from "path";

/**
 * Serves the import map generated by `@repo/shared-runtime`.
 */

const IMPORTMAP_PATH = path.resolve(
  __dirname,
  "../public/assets/shared/importmap.json",
);

type ImportMap = { imports: Record<string, string> };

let cached: string | null = null;

const readImportMap = (): string => {
  // Cached in production
  if (cached !== null && process.env.NODE_ENV === "production") {
    return cached;
  }

  let map: ImportMap;
  try {
    map = JSON.parse(readFileSync(IMPORTMAP_PATH, "utf8")) as ImportMap;
  } catch (e) {
    throw new Error(
      `Could not read the shared import map at ${IMPORTMAP_PATH}. ` +
        `Run \`yarn workspace @repo/shared-runtime build\` to generate it. ` +
        `Without it, every externalized import in the apps and plugin bundles ` +
        `will fail to resolve in the browser. (${String(e)})`,
    );
  }

  cached = JSON.stringify(map, null, 2);
  return cached;
};

export const getImportMapTag = (): string =>
  `<script type="importmap" nonce="INJECT_NONCE">\n${readImportMap()}\n</script>`;
