import react from "@vitejs/plugin-react-swc";
import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { OutputChunk, RollupOutput } from "rollup";
import {
  build,
  defineConfig,
  type InlineConfig,
  type UserConfigFnPromise,
} from "vite";

import {
  isSharedModule,
  SHARED_MODULES,
  type SharedModule,
} from "@repo/shared-modules";
import { importmapPlugin } from "./importmap-plugin";

// Builds the single shared module named by the MODULE env var into one hashed
// ESM file, externalizing every other shared specifier. See README.md.

const OUT_DIR = resolve(
  __dirname,
  "../../backend/server/public/assets/shared",
);

// Real files rather than virtual modules: Vite resolves `lib.entry` as a
// filesystem path before plugin `resolveId` hooks run. Gitignored.
const GENERATED_DIR = resolve(__dirname, ".generated");

/**
 * Resolution for both the real build and the export-shape probe. Must be shared
 * or the probe answers a question about a different file; see README.md.
 */
const SHARED_RESOLVE = {
  mainFields: ["module", "browser", "main"],
  conditions: ["import", "browser", "default"],
} satisfies InlineConfig["resolve"];

/**
 * Whether the target really has a default export, decided by asking Vite rather
 * than by static analysis, since every cheap heuristic disagrees with the
 * bundler for some package on the list. See README.md.
 */
const hasRealDefaultExport = async (
  target: string,
  sharedResolve: InlineConfig["resolve"],
): Promise<boolean> => {
  // A real entry file, because `lib.entry` set to a bare specifier is compared
  // against the `external` predicate before resolution. A missing default makes
  // Rollup fail, which is the signal wanted, so the failure is caught.
  mkdirSync(GENERATED_DIR, { recursive: true });
  const probePath = join(GENERATED_DIR, ".probe.js");
  writeFileSync(probePath, `export { default } from ${JSON.stringify(target)};\n`);

  try {
    await build({
      logLevel: "silent",
      // Critical: without this the nested build re-reads THIS config file and
      // recurses until the process hangs.
      configFile: false,
      resolve: sharedResolve,
      build: {
        write: false,
        target: "esnext",
        minify: false,
        lib: { entry: probePath, formats: ["es"], fileName: "probe" },
      },
    });
    return true;
  } catch {
    return false;
  }
};

const writeEntryFile = async (
  mod: SharedModule,
  safeName: string,
  sharedResolve: InlineConfig["resolve"],
): Promise<string> => {
  const target = mod.entry ?? mod.specifier;
  const spec = JSON.stringify(target);

  // For a CJS package `export *` forwards nothing, so named exports are listed.
  const named = mod.namedExports?.length
    ? `export { ${mod.namedExports.join(", ")} } from ${spec};`
    : `export * from ${spec};`;

  const aliases = Object.entries(mod.exportAliases ?? {}).map(
    ([exported, source]) => `export { ${source} as ${exported} } from ${spec};`,
  );

  const contents = [
    `// Generated by vite.config.ts. Do not edit.`,
    named,
    ...aliases,
    (await hasRealDefaultExport(target, sharedResolve))
      ? `export { default } from ${spec};`
      : null,
  ]
    .filter(Boolean)
    .join("\n");

  mkdirSync(GENERATED_DIR, { recursive: true });
  const entryPath = join(GENERATED_DIR, `${safeName}.js`);
  writeFileSync(entryPath, contents + "\n");
  return entryPath;
};

const config: UserConfigFnPromise = async ({ mode }) => {
  const requested = process.env.MODULE;
  const mod = SHARED_MODULES.find((m) => m.specifier === requested);
  if (!mod) {
    throw new Error(
      `MODULE env var must be one of:\n${SHARED_MODULES.map((m) => "  " + m.specifier).join("\n")}`,
    );
  }

  const safeName = mod.specifier.replace(/^@/, "").replace(/[/]/g, "__");
  const entryPath = await writeEntryFile(mod, safeName, SHARED_RESOLVE);

  return {
    plugins: [react(), importmapPlugin({ module: mod, outDir: OUT_DIR })],
    define: {
      "process.env.NODE_ENV": JSON.stringify(
        mode === "development" ? "development" : "production",
      ),
    },
    build: {
      outDir: OUT_DIR,
      emptyOutDir: false,
      target: "esnext",
      minify: true,
      // ~2x the JS on disk; SHARED_RUNTIME_NO_MAPS skips them.
      sourcemap: !process.env.SHARED_RUNTIME_NO_MAPS,
      lib: {
        entry: entryPath,
        formats: ["es"],
        fileName: () => `${safeName}.mjs`,
      },
      rollupOptions: {
        // `self` is passed so this module never imports itself.
        external: (id: string) => isSharedModule(id, mod.specifier),
        output: {
          entryFileNames: `${safeName}-[hash].mjs`,
          chunkFileNames: `${safeName}-chunk-[hash].mjs`,
          assetFileNames: `${safeName}-[hash][extname]`,
        },
      },
    },
    resolve: SHARED_RESOLVE,
  };
};

export default defineConfig(config);
