fragment MediaWithMediaDependency on Media {
  id
  ...Media
  imageMetadata: mediaImageMetadatumByImageMediaId {
    width
    height
  }
  videoMetadata: mediaVideoMetadatumByVideoMediaId {
    duration
    hlsMediaId
    thumbnailMediaId
    transcodeStatus
    transcodeProgress
    transcodeStage
    transcodeStageProgress
  }
  audioMetadata: mediaAudioMetadatumByAudioMediaId {
    duration
    playbackMediaId
    coverMediaId
    playbackMedia {
      id
      mediaName
    }
    coverMedia {
      id
      mediaName
    }
    title
    artist
    album
    transcodeStatus
    transcodeProgress
  }
  dependencies: mediaDependenciesByParentMediaId {
    totalCount
    nodes {
      childMedia {
        id
        mediaName
        fileExtension
      }
    }
  }
}
