/**
 * Songs seeded into the church (lyrics) demo, each with its own motion
 * background, streamed from Mux over HLS.
 *
 * `content` uses the lyrics plugin's format: `[Section]` headings, one line
 * per lyric line, and a lone `-` to split a section into another slide.
 */
export type DemoSong = {
  title: string;
  author: string;
  /** Mux playback id of the motion background */
  muxPlaybackId: string;
  backgroundTitle: string;
  backgroundDuration: number;
  content: string;
};

export const DEMO_SONGS: DemoSong[] = [
  {
    title: "The Heart of Worship",
    author: "Matt Redman",
    muxPlaybackId: "riEMCQNCB7VE2gL00P8Zxjhyxhujk5ouG4FXPZOjY00zs",
    backgroundTitle: "Painted Stars",
    backgroundDuration: 10,
    content: [
      "[Verse 1]",
      "[D]When the music [A]fades",
      "All is stripped[Em] away",
      "And I simply [A]come",
      "-",
      "[D]Longing just to [A]bring",
      "something that's o[Em]f worth",
      "That will bless You[A]r heart",
      "",
      "[Pre-Chorus]",
      "[Em]I'll bring You [D/F#]more than a[A] song",
      "For a [Em]song in itself",
      "[D/F#]is not what You have[A] required",
      "-",
      "[Em]You search much[D/F#] deeper [A]within",
      "Through the way things appear",
      "[Em]You're looking [D/F#]into my [A]heart",
      "",
      "[Chorus]",
      "[D]I'm coming back to the[A/C#] heart of worship",
      "And it's [Em]all about You, it's[G] all about [A]You",
      "[D]Jesus",
      "-",
      "[D]I'm sorry, Lord, for the[A/C#] thing I've made it",
      "When it's [Em]all about You, it's[G] all about [A]You",
      "[D]Jesus",
      "",
      "[Verse 2]",
      "[D]King of endless [A]worth",
      "no one could[Em] express",
      "How much You[A] deserve",
      "-",
      "[D]Though I'm weak and[A] poor",
      "all I have is[Em] Yours",
      "Ev'ry single[A] breath",
    ].join("\n"),
  },
  {
    title: "Build My Life",
    author: "Housefires",
    muxPlaybackId: "Vi5BsWORkdan7wLuUF1lLwjXHpRnmabv45vINP0002HOc",
    backgroundTitle: "Retrograde",
    backgroundDuration: 11,
    content: [
      "[Verse 1]",
      "[G] Worthy of every s[C/G]ong",
      "We could ever sing",
      "[G/B] Worthy of all the pr[C/G]aise",
      "We could ever bring",
      "-",
      "[G] Worthy of every br[C/G]eath",
      "We could ever breathe",
      "We live for You",
      "",
      "[Verse 2]",
      "[G] Jesus, the Name",
      "Ab[C/G]ove every other name",
      "[G/B] Jesus, the only On[C/G]e",
      "Who could ever save",
      "-",
      "[G] Worthy of every br[C/G]eath",
      "We could ever breathe",
      "We live for Y[G/B]ou",
      "Oh, we live for [C/G]You",
      "",
      "[Chorus]",
      "[Cmaj9]Holy, there is no one[Am7] like You",
      "There is none b[G]eside You",
      "Open up my[Em7] eyes in wonder",
      "-",
      "[Cmaj9]Show me who You are and[Am7] fill me",
      "With Your heart and[G] lead me",
      "In Your love t[Em7]o those around m[Cmaj9]e",
      "",
      "[Bridge]",
      "[Cmaj9]I will build my l[Dsus]ife upon Your l[Em7]ove",
      "It is a [G/B]firm foundation",
      "[Cmaj9]I will put my tr[Dsus]ust in You al[Em7]one",
      "And I will [G/B]not be shaken",
    ].join("\n"),
  },
  {
    title: "Shout to the Lord",
    author: "Darlene Zschech",
    muxPlaybackId: "W8C5txxLJfCrkTUzbXUbM5NMGAKc6v4Xw9Ph1P4Qdp00",
    backgroundTitle: "Star Blast",
    backgroundDuration: 10,
    content: [
      "[Verse]",
      "[G]My Jesus[D], My Savio[Em]r,",
      "Lord there is [D]none like [C]you",
      "All of my day[G]s, I[C] want to p[G]raise",
      "The [Em]wonders of your [F]mighty lo[D]ve",
      "-",
      "[G]My comfort,[D] My shelter[Em]",
      "Tower of re[D]fuge and stren[C]gth",
      "Let every brea[G]th, [C]all that I [G]am",
      "[Em]never cease to [F]worship [D]you",
      "",
      "[Chorus]",
      "[G]Shout to the [Em]Lord",
      "All the e[C]arth let us sin[D]g",
      "[G]Power and [Em]majesty",
      "[C]Praise to the ki[D]ng",
      "-",
      "[Em]Mountains bow down",
      "And the s[C]eas will roar",
      "At the s[D]ound o[Em]f your na[D]me",
      "-",
      "[G]I sing for[Em] joy",
      "At the w[C]ork of your h[D]ands",
      "[G]Forever I'll [Em]love you",
      "[C]Forever I'll s[D]tand",
      "[Em]Nothing compares to the",
      "P[C]romise I h[D]ave in Y[G]ou",
    ].join("\n"),
  },
];
