name: Run Tauri Build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
            tauri/yarn.lock
            tauri/node-server/yarn.lock
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: yarn, lint, build and test
        shell: bash
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        run: |
          # Build TOP
          cp .env.ci .env
          yarn --no-immutable
          yarn build

          # Reduce size
          node scripts/build_utils/extract_core.js
          node scripts/build_utils/extract_server.js
          node scripts/build_utils/extract_plugins.js
          node scripts/build_utils/extract_tauri.js
          node scripts/build_utils/copy_deps.js

          # Move the node_modules
          rm -rf node_modules
          cp -r ./node_modules_nft/node_modules ./node_modules
          cp -r ./apps/homepage/.next/standalone/node_modules/* ./node_modules

          # Cleanup
          rm -rf node_modules_nft

          # And Next.js stuff
          cp -r apps/homepage/.next/standalone/apps/homepage homepage_temp
          cp -r apps/homepage/.next/static next_static_temp
          rm -rf apps/homepage
          mv homepage_temp apps/homepage
          mv next_static_temp apps/homepage/.next/static

          cd tauri
          yarn --no-immutable

          yarn tauri build --verbose

          echo "tauri_path=$(pwd)" >> "$GITHUB_ENV"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-${{ matrix.platform }}${{ matrix.args }}
          path: |
            /a/TheOpenPresenter/TheOpenPresenter/tauri/target/release/bundle/nsis/TheOpenPresenter_0.1.0_x64-setup.exe
            /a/TheOpenPresenter/TheOpenPresenter/tauri/target/release/bundle/msi/TheOpenPresenter_0.1.0_x64_en-US.msi
            /Users/runner/work/TheOpenPresenter/TheOpenPresenter/tauri/target/release/bundle/dmg/TheOpenPresenter_0.1.0_aarch64.dmg
            /Users/runner/work/TheOpenPresenter/TheOpenPresenter/tauri/target/release/bundle/macos/TheOpenPresenter.app

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Desktop App Nightly Release $$'
          prerelease: true
          body: 'This is a nightly release of TheOpenPresenter desktop app. Please use with caution.'
          files: |
            /home/runner/work/TheOpenPresenter/TheOpenPresenter/artifacts/**/*.exe
            /home/runner/work/TheOpenPresenter/TheOpenPresenter/artifacts/**/*.msi
            /home/runner/work/TheOpenPresenter/TheOpenPresenter/artifacts/**/*.dmg
      - name: Release Tag
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            /home/runner/work/TheOpenPresenter/TheOpenPresenter/artifacts/**/*.exe
            /home/runner/work/TheOpenPresenter/TheOpenPresenter/artifacts/**/*.msi
            /home/runner/work/TheOpenPresenter/TheOpenPresenter/artifacts/**/*.dmg