name: Run Tauri Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
            tauri/yarn.lock
            tauri/node-server/yarn.lock
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: yarn, lint, build and test
        shell: bash
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        run: |
          pwd
          cd ../..

          mv ./TheOpenPresenter/TheOpenPresenter/tauri ./tauri
          cp -r ./TheOpenPresenter/TheOpenPresenter ./tauri/node-server/theopenpresenter

          cd tauri/node-server/theopenpresenter
          cp .env.ci .env
          yarn --no-immutable
          yarn build
          cd ..
          
          yarn --no-immutable
          cd ..
          yarn --no-immutable

          # TODO: Download Node
          yarn tauri build --verbose